export const quotes = [
  "If you want to cultivate a habit, do it without any reservation, till it is firmly established. Until it is so confirmed, until it becomes a part of your character, let there be no exception, no relaxation of effort.",
  "Without struggle, no progress and no result. Every breaking of habit produces a change in the machine.",
  "We can use decision-making to choose the habits we want to form, use willpower to get the habit started, then – and this is the best part – we can allow the extraordinary power of habit to take over. At that point, we’re free from the need to decide and the need to use willpower.",
  "Habit is a cable; we weave a thread of it each day, and at last we cannot break it.",
  "Whatever you want to do, if you want to be great at it, you have to love it and be able to make sacrifices for it.",
  "Any act often repeated soon forms a habit; and habit allowed, steady gains in strength, At first it may be but as a spider’s web, easily broken through, but if not resisted it soon binds us with chains of steel.",
  "There is just no getting around that turning bad things into good things is up to you.",
  "Sow an act and you reap a habit. Sow a habit and you reap a character. Sow a character and you reap a destiny.",
  "We can do anything we want to if we stick to it long enough.",
  "I just never, ever want to give up. Most battles are won in the 11th hour, and most people give up. If you give up once, it’s quite hard. If you give up a second time, it’s a little bit easier. Give up a third time, it’s starting to become a habit.",
  "To enjoy freedom we have to control ourselves.",
  "You can start right where you stand and apply the habit of going the extra mile by rendering more service and better service than you are now being paid for.",
  "Moral excellence comes about as a result of habit. We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.",
  "Creativity is a habit, and the best creativity is the result of good work habits.",
  "If you are going to achieve excellence in big things, you develop the habit in little matters. Excellence is not an exception, it is a prevailing attitude.",
  "The chains of habit are too weak to be felt until they are too strong to be broken.",
  "Good habits are worth being fanatical about.",
  "Our character is basically a composite of our habits. Because they are consistent, often unconscious patterns, they constantly, daily, express our character.",
  "The best kind of happiness is a habit you’re passionate about.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "The difference between an amateur and a professional is in their habits. An amateur has amateur habits. A professional has professional habits. We can never free ourselves from habit. But we can replace bad habits with good ones.",
  "Self-reflection is a much kinder teacher than regret is. Prioritize yourself by making a habit of it.",
  "Self-discipline is an act of cultivation. It requires you to connect today’s actions to tomorrow’s results. There’s a season for sowing a season for reaping. Self-discipline helps you know which is which.",
  "Don’t try to rush progress. Remember—a step forward, no matter how small, is a step in the right direction. Keep believing.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Courage is like—it’s a habitus, a habit, a virtue: You get it by courageous acts. It’s like you learn to swim by swimming. You learn courage by couraging.",
  "Habits are powerful, but delicate. They can emerge outside our consciousness, or can be deliberately designed. They often occur without our permission, but can be reshaped by fiddling with their parts. They shape our lives far more than we realize—they are so strong, in fact, that they cause our brains to cling to them at the exclusion of all else, including common sense.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.",
  "People who cannot invent and reinvent themselves must be content with borrowed postures, secondhand ideas, fitting in instead of standing out.",
  "The best way to change it is to do it, right? And then after a while you become it, and it’s easy.",
  "Your beliefs become your thoughts, your thoughts become your words, your words become your actions, your actions become your habits, your habits become your values, your values become your destiny.",
  "The research and advice from top experts is clear. Investing in small changes, in incremental steps, is the smart approach to getting better.",
  "True integrity requires no spotlight. To really train the integrity habit into our leadership, we must learn to do the right thing even when nobody’s looking.",
  "When we make a consistent practice of choosing the courageous response, courage becomes a habit. And that habit has the power to transform our leadership.",
  "At the end of the day, practices make the difference; they transform thoughts into action. It may seem impossible to summon the same mental strength as your mentor. But when you think about what they did, not who they are, suddenly capturing their spirit in your own leadership seems much more doable.",
  "In leadership, there are few things more powerful than letting people know how much you care, and allowing that caring to guide your approach to delivering results."
]
export const authors = [
  "Mahavira",
  "George Gurdjieff",
  "Gretchen Rubin",
  "Horace Mann",
  "Dr. Maya Angelou",
  "Tyron Edwards",
  "Deepak Chopra",
  "Charles Reade",
  "Helen Keller",
  "Lewis Gordon Pugh",
  "Virginia Woolf",
  "Napoleon Hill",
  "Aristotle",
  "Twyla Tharp",
  "Colin Powell",
  "Samuel Johnson",
  "John Irving",
  "Stephen Covey",
  "Shannon L. Adler",
  "Jim Ryun",
  "Steven Pressfield",
  "Andrena Sawyer",
  "Gary Ryan Blair",
  "Kara Goucher",
  "Will Durant (paraphrasing Aristotle)",
  "Brené Brown",
  "Charles Duhigg",
  "Oprah",
  "Benjamin Franklin",
  "Warren Bennis",
  "Ursula Burns",
  "Gandhi",
  "Doug Conant",
  "Doug Conant",
  "Doug Conant",
  "Doug Conant",
  "Doug Conant"
]
